server:
 port: 1116

#spring:
#  cloud:
#   gateway:
#    routes:
    #------------------------------------------------------------------------
#    - id: helloservice
#      uri: http://localhost:3330
#      predicates:
#      - path: /helloservice/**
#------------------------------------------------------------------------
#      - id: fegin
#        uri: http://localhost:5555
#        predicates:
#          - path:/fegin/**

spring:
  cloud:
    gateway:
      routes:
      - id: helloservice
        uri: http://localhost:3330
        predicates: #The Path Route Predicate Factory takes one parameter: a Spring PathMatcher pattern.
        - Path=/helloservice/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka/,http://${eureka.instance.hostname}:1111/eureka/



