server:
  port: 1116

spring:
  application:
    name: mygateway
  cloud:
    gateway:
      discovery:
        locator:
          #  是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例
          # 。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          enabled: true

      routes:
      #------------------------------------------------------------------------
      - id: helloservice
        uri: http://localhost:3330
        predicates:
          - path:/helloservice/**
      #------------------------------------------------------------------------
#      - id: fegin
#        uri: http://localhost:5555
#        predicates:
#          - path:/fegin/**

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka/,http://${eureka.instance.hostname}:1111/eureka/



