server:
  port: 20813

eureka:
  server:
      enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:20812/eureka/
  instance:
    preferIpAddress: true
    hostname: 118.25.54.103
    lease-renewal-interval-in-seconds: 30 #参数用于定义服务续约任务的调用间隔时间
    lease-expiration-duration-in-seconds: 90 #参数用于定义服务失效的时间，默认为90秒。
    metadata-map:
      yan: yan
    #instance-id: ${eureka.instance.hostname}:${server.port}

