server.port=1117

spring:
#redis
  redis:
    database: 0
    host: 118.25.54.103
    port: 6380
    password: dfth@2018
    timeout: 10000
    pool:
      max-active: 150
      max-wait: 3000
      max-idle: 30


