server:
  port: 4444

spring:
  application:
    name: springcloudprovide
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yan.springcloudprovide.entity

#showSql
logging:
  level:
    com:
      yan:
        springcloudprovide:
          mapper: debug