#Matser的ip地址


spring:
  redis:
    host: 118.25.54.103
    port: 6379
    password: dfth@2018
    timeout: 10000
    pool:
       max-wait: 100000
       min-idle: 0
       max-active: 100
       max-idle: 10


