server:
  port: 4444

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yan.springcloudprovide.entity

#showSql
logging:
  level:
    com:
      yan:
        springcloudprovide:
          mapper: debug